import type { CoffeeRecipe, CoffeeTip } from "./types";

export const coffeeRecipes: CoffeeRecipe[] = [
  {
    name: "Hario V60 — Classic",
    equipment: "Hario V60 02, paper filter, gooseneck kettle",
    coffee: "18g", grind: "Medium-fine (sea salt)", water: "300g at 93°C", ratio: "1:16.7",
    steps: [
      { stage: "Rinse filter", detail: "Pour hot water through filter, discard", time: "0:00" },
      { stage: "Bloom", detail: "Pour 50g water in spirals, swirl gently", time: "0:00–0:45" },
      { stage: "First pour", detail: "Pour to 150g in slow concentric circles", time: "0:45–1:15" },
      { stage: "Second pour", detail: "Pour to 250g, centre to edge", time: "1:15–1:45" },
      { stage: "Final pour", detail: "Pour to 300g, gentle pulse", time: "1:45–2:10" },
      { stage: "Drawdown", detail: "Let drain fully, give a gentle swirl", time: "2:10–3:00" },
    ],
    tip: "If it drains too fast, go finer. Too slow? Go coarser. Aim for 2:45–3:15 total.",
  },
  {
    name: "Kalita Wave — Sweet & Balanced",
    equipment: "Kalita Wave 185, wave filter, gooseneck kettle",
    coffee: "20g", grind: "Medium (table salt)", water: "320g at 92°C", ratio: "1:16",
    steps: [
      { stage: "Rinse filter", detail: "Rinse thoroughly — wave filters need a good soak", time: "0:00" },
      { stage: "Bloom", detail: "Pour 50g, stir gently with spoon", time: "0:00–0:40" },
      { stage: "First pour", detail: "Pour to 160g in steady centre pour", time: "0:40–1:10" },
      { stage: "Second pour", detail: "Pour to 240g, keep water level steady", time: "1:10–1:40" },
      { stage: "Final pour", detail: "Pour to 320g, small gentle pulses", time: "1:40–2:10" },
      { stage: "Drawdown", detail: "Flat bed = even extraction", time: "2:10–3:30" },
    ],
    tip: "Flat bottom gives more forgiveness than a V60 — great for medium roasts.",
  },
  {
    name: "Chemex — Clean & Bright",
    equipment: "Chemex 6-cup, Chemex bonded filter, gooseneck kettle",
    coffee: "30g", grind: "Medium-coarse (kosher salt)", water: "500g at 94°C", ratio: "1:16.7",
    steps: [
      { stage: "Rinse filter", detail: "Thick side faces spout, rinse well & discard", time: "0:00" },
      { stage: "Bloom", detail: "Pour 60g in circles, let CO₂ release", time: "0:00–0:45" },
      { stage: "First pour", detail: "Slow spirals to 250g, keep slurry even", time: "0:45–1:45" },
      { stage: "Second pour", detail: "Pour to 400g, steady and central", time: "1:45–2:45" },
      { stage: "Final pour", detail: "Top up to 500g in gentle pulses", time: "2:45–3:15" },
      { stage: "Drawdown", detail: "Full drain — expect 4:00–4:30 total", time: "3:15–4:30" },
    ],
    tip: "Thick Chemex filter removes oils for tea-like clarity. Don't rush the bloom.",
  },
  {
    name: "Origami — Vibrant & Complex",
    equipment: "Origami dripper, Kalita or conical filter, gooseneck kettle",
    coffee: "15g", grind: "Medium-fine (finer than V60)", water: "250g at 91°C", ratio: "1:16.7",
    steps: [
      { stage: "Rinse filter", detail: "Use Kalita wave or conical filter — rinse well", time: "0:00" },
      { stage: "Bloom", detail: "Pour 40g, aggressive swirl to saturate", time: "0:00–0:35" },
      { stage: "Single pour", detail: "Pour to 250g in one continuous slow spiral", time: "0:35–1:45" },
      { stage: "Drawdown", detail: "Light swirl, let drain completely", time: "1:45–2:30" },
    ],
    tip: "Ridges increase airflow — try a wave filter for a sweeter cup.",
  },
  {
    name: "April Brewer — Delicate & Juicy",
    equipment: "April Brewer, April filter, gooseneck kettle",
    coffee: "16g", grind: "Medium (between V60 and Kalita)", water: "260g at 90°C", ratio: "1:16.3",
    steps: [
      { stage: "Rinse filter", detail: "Place filter with tabs up, rinse gently", time: "0:00" },
      { stage: "Bloom", detail: "Pour 50g, no swirl — let it be", time: "0:00–0:40" },
      { stage: "Pulse 1", detail: "Pour to 130g in centre stream", time: "0:40–1:00" },
      { stage: "Pulse 2", detail: "Pour to 200g after slight pause", time: "1:10–1:30" },
      { stage: "Pulse 3", detail: "Final pour to 260g", time: "1:40–2:00" },
      { stage: "Drawdown", detail: "Slow drain — expect 2:45–3:15 total", time: "2:00–3:15" },
    ],
    tip: "Lower temp brings out fruit-forward notes. Perfect for light roast single origins.",
  },
  {
    name: "Tricolate — Zero Agitation",
    equipment: "Tricolate brewer, Tricolate filter, kettle",
    coffee: "18g", grind: "Fine (espresso-leaning)", water: "360g at 95°C", ratio: "1:20",
    steps: [
      { stage: "Rinse filter", detail: "Lock filter in, rinse with boiling water", time: "0:00" },
      { stage: "Add coffee", detail: "Level bed, no tapping — keep it flat", time: "0:00" },
      { stage: "Single pour", detail: "Pour all 360g onto dispersion screen", time: "0:00–0:20" },
      { stage: "Wait", detail: "Walk away — gravity does the work", time: "0:20–6:00" },
      { stage: "Serve", detail: "Full immersion + percolation hybrid", time: "~6:00" },
    ],
    tip: "1:20 ratio and fine grind. Long contact time + zero agitation = impossibly sweet.",
  },
];

export const coffeeTips: CoffeeTip[] = [
  { type: "tip", text: "Always rinse your paper filter — removes papery taste and preheats the brewer." },
  { type: "fact", text: "Coffee is the world's second most traded commodity after crude oil." },
  { type: "tip", text: "Store beans airtight at room temperature. Never the fridge — moisture is the enemy." },
  { type: "fact", text: "Ideal brewing water is 150ppm TDS. Too soft = sour, too hard = flat and chalky." },
  { type: "tip", text: "Bloom for 30–45 seconds. The CO₂ release means your beans are fresh." },
  { type: "fact", text: "Ethiopia's Yirgacheffe produces coffee with natural blueberry and jasmine notes." },
  { type: "tip", text: "Grind right before brewing. Coffee goes stale within 15 minutes of grinding." },
  { type: "fact", text: "A peaberry is a single seed in a coffee cherry — prized for concentrated flavour." },
  { type: "tip", text: "Sour = under-extracted. Try grinding finer or increasing water temperature." },
  { type: "fact", text: "Light roast has slightly more caffeine than dark — roasting burns it off." },
  { type: "tip", text: "Weigh your water. Even 10g off changes the ratio and flavour significantly." },
  { type: "fact", text: "First wave = instant. Second wave = Starbucks. Third wave treats coffee like wine." },
  { type: "tip", text: "Swirl your V60 after pouring — levels the bed for more even extraction." },
  { type: "fact", text: "Panama Geisha beans sell for over $2,000/kg. Tropical fruit and bergamot notes." },
  { type: "tip", text: "Temp matters: 88–92°C for light roasts, 90–94°C for medium, 85–90°C for dark." },
  { type: "tip", text: "A burr grinder is the single biggest upgrade. Blades create uneven particles." },
  { type: "fact", text: "'Cappuccino' comes from Capuchin monks — their brown hoods matched the drink." },
  { type: "tip", text: "Bitter = over-extracted. Try a coarser grind or lower water temperature." },
  { type: "fact", text: "Kopi Luwak isn't actually good coffee — over-fermented and flat. Pure marketing." },
];
